---
- name: Restart spooler and install software
  hosts: windows
  
  vars_files:
  - vars/windowssecrets.yml
  
  tasks:
    - name: Install winfetch and 7-zip through Chocolatey
      win_chocolatey:
       state: present
       name:
        - winfetch
        - 7zip

    - name: Restart the print spooler service
      win_shell: Restart-Service -Name spooler

    - name: Create local user
      win_user:
       name: '{{ item.name }}'
       password: '{{ item.password }}'
       groups: Users
       update_password: on_create
       password_never_expires: true
 
      loop:
       - name: tom
         password: Password1
       - name: jerry
         password: Password2

    - name: Show common values
      debug:
         msg: "host={{ inventory_hostname }}, user={{ ansible_user }}, os={{ ansible_facts['os_family'] }}"
